# Generated by Django 4.2.7 on 2023-11-05 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=120)),
                ('project_description', models.TextField()),
                ('total_task_count', models.IntegerField(default=0)),
                ('completed_task_count', models.IntegerField(default=0)),
                ('not_completed_task_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not_Completed', 'Not_Completed'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Not_Completed', max_length=30)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('task_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.TextField()),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Not_Completed', 'Not_Completed'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Not_Completed', max_length=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assign_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task_app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=task_app.models.GenerateAttachmentPath())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='task_app.task')),
            ],
        ),
    ]
