# Generated by Django 4.2.7 on 2023-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_task_assign_to_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
    ]
