# Generated by Django 4.2.7 on 2023-11-08 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_projects_inprogress_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='inprogress_task_count',
        ),
        migrations.AddField(
            model_name='projects',
            name='task',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Not_Completed', 'Not_Completed'), ('Completed', 'Completed')], default='Not_Completed', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not_Completed', 'Not_Completed'), ('Completed', 'Completed')], default='Not_Completed', max_length=30),
        ),
    ]
