# Generated by Django 4.2.7 on 2023-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_remove_projects_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
