# Generated by Django 4.2.7 on 2023-11-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_projects_task_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.task'),
        ),
    ]
