# Generated by Django 4.2.7 on 2023-11-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0017_alter_projects_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.task'),
        ),
    ]
