# Generated by Django 4.2.7 on 2023-11-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0018_alter_projects_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='task',
        ),
    ]
