# Generated by Django 4.2.7 on 2023-11-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
        ('task_app', '0019_remove_projects_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='user_app.profile'),
            preserve_default=False,
        ),
    ]
